# Generated by Django 4.1.3 on 2022-11-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
