# Generated by Django 4.1.3 on 2023-01-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='loyalty_points_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
